openapi: 3.0.0
info:
  title: API de Usuários
  version: 1.0.0
  description: Documentação da API de usuários com Swagger
servers:
  - url: http://localhost:3333
    description: Servidor de desenvolvimento

paths:
  /users.json:
    get:
      summary: Retorna a lista de todos os usuários
      tags:
        - Usuários
      responses:
        '200':
          description: Uma lista de usuários.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    nome:
                      type: string
                    sobrenome:
                      type: string
                    idade:
                      type: integer
                    profissao:
                      type: string
                    cidade:
                      type: string
                    estado:
                      type: string
    post:
      summary: Adiciona um novo usuário
      tags:
        - Usuários
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                sobrenome:
                  type: string
                idade:
                  type: integer
                profissao:
                  type: string
                cidade:
                  type: string
                estado:
                  type: string
      responses:
        '201':
          description: O usuário foi criado com sucesso.
        '400':
          description: Dados de entrada inválidos.

  /users.json/{id}:
    put:
      summary: Atualiza um usuário existente pelo ID
      tags:
        - Usuários
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: O ID do usuário a ser atualizado.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                sobrenome:
                  type: string
                idade:
                  type: integer
                profissao:
                  type: string
                cidade:
                  type: string
                estado:
                  type: string
      responses:
        '200':
          description: O usuário foi atualizado com sucesso.
        '400':
          description: Dados de entrada inválidos.
        '404':
          description: Usuário não encontrado.
    delete:
      summary: Deleta um usuário pelo ID
      tags:
        - Usuários
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: O ID do usuário a ser deletado.
      responses:
        '204':
          description: O usuário foi deletado com sucesso.
        '404':
          description: Usuário não encontrado.
